name: Sentry Trigger

on:
  schedule:
    # Runs at 00:00 UTC (4:00 PM PST) every day
    - cron: '0 0 * * *'
  # Allows you to click "Run workflow" manually in GitHub for testing
  workflow_dispatch:

jobs:
  wake_up_sentry:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Sentry Scan
        run: |
          curl -X GET https://livelaughlau.de/api/sentry-scan